server:
  port: 9999
#  servlet:
#    context-path: /gateway_service

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
    database: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-demo
          uri: lb://service-demo  # lb://是指当前注册中心下 后面的是微服务名字
          predicates:
            - Path=/gateway-home/service-demo/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}' # 用于限流的键的解析器的 Bean 对象的名字
                redis-rate-limiter.replenishRate: 1     # 令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3     # 令牌桶的容量



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7007/eureka/eureka
#  prefer-ip-address: true     #将IP注册到eureka中，如果为false默认注册主机名